export const boards = [
    {
    "1:1": { status: false, letter: "" },
    "1:2": { status: false, letter: "" },
    "1:3": { status: false, letter: "" },
    "1:4": { status: false, letter: "" },
    "1:5": { status: false, letter: "" },
    "1:6": { status: false, letter: "" },
    "1:7": { status: false, letter: "" },
    "1:8": { status: false, letter: "" },
    "1:9": { status: false, letter: "" },
    "1:10": { status: false, letter: "" },

    "2:1": { status: false, letter: "" },
    "2:2": { status: false, letter: "" },
    "2:3": { status: false, letter: "" },
    "2:4": { status: false, letter: "" },
    "2:5": { status: false, letter: "" },
    "2:6": { status: false, letter: "" },
    "2:7": { status: false, letter: "" },
    "2:8": { status: false, letter: "" },
    "2:9": { status: false, letter: "" },
    "2:10": { status: false, letter: "" },

    "3:1": { status: false, letter: "" },
    "3:2": { status: false, letter: "" },
    "3:3": { status: false, letter: "" },
    "3:4": { status: false, letter: "" },
    "3:5": { status: false, letter: "" },
    "3:6": { status: false, letter: "" },
    "3:7": { status: false, letter: "" },
    "3:8": { status: false, letter: "" },
    "3:9": { status: false, letter: "" },
    "3:10": { status: false, letter: "" },

    "4:1": { status: false, letter: "" },
    "4:2": { status: false, letter: "" },
    "4:3": { status: false, letter: "" },
    "4:4": { status: false, letter: "" },
    "4:5": { status: false, letter: "" },
    "4:6": { status: false, letter: "" },
    "4:7": { status: false, letter: "" },
    "4:8": { status: false, letter: "" },
    "4:9": { status: false, letter: "" },
    "4:10": { status: false, letter: "" },

    "5:1": { status: false, letter: "" },
    "5:2": { status: false, letter: "" },
    "5:3": { status: false, letter: "" },
    "5:4": { status: false, letter: "" },
    "5:5": { status: false, letter: "" },
    "5:6": { status: false, letter: "" },
    "5:7": { status: false, letter: "" },
    "5:8": { status: false, letter: "" },
    "5:9": { status: false, letter: "" },
    "5:10": { status: false, letter: "" },

    "6:1": { status: false, letter: "" },
    "6:2": { status: false, letter: "" },
    "6:3": { status: false, letter: "" },
    "6:4": { status: false, letter: "" },
    "6:5": { status: false, letter: "" },
    "6:6": { status: false, letter: "" },
    "6:7": { status: false, letter: "" },
    "6:8": { status: false, letter: "" },
    "6:9": { status: false, letter: "" },
    "6:10": { status: false, letter: "" },

    "7:1": { status: false, letter: "" },
    "7:2": { status: false, letter: "" },
    "7:3": { status: false, letter: "" },
    "7:4": { status: false, letter: "" },
    "7:5": { status: false, letter: "" },
    "7:6": { status: false, letter: "" },
    "7:7": { status: false, letter: "" },
    "7:8": { status: false, letter: "" },
    "7:9": { status: false, letter: "" },
    "7:10": { status: false, letter: "" },

    "8:1": { status: false, letter: "" },
    "8:2": { status: false, letter: "" },
    "8:3": { status: false, letter: "" },
    "8:4": { status: false, letter: "" },
    "8:5": { status: false, letter: "" },
    "8:6": { status: false, letter: "" },
    "8:7": { status: false, letter: "" },
    "8:8": { status: false, letter: "" },
    "8:9": { status: false, letter: "" },
    "8:10": { status: false, letter: "" },

    "9:1": { status: false, letter: "" },
    "9:2": { status: false, letter: "" },
    "9:3": { status: false, letter: "" },
    "9:4": { status: false, letter: "" },
    "9:5": { status: false, letter: "" },
    "9:6": { status: false, letter: "" },
    "9:7": { status: false, letter: "" },
    "9:8": { status: false, letter: "" },
    "9:9": { status: false, letter: "" },
    "9:10": { status: false, letter: "" },

    "10:1": { status: false, letter: "" },
    "10:2": { status: false, letter: "" },
    "10:3": { status: false, letter: "" },
    "10:4": { status: false, letter: "" },
    "10:5": { status: false, letter: "" },
    "10:6": { status: false, letter: "" },
    "10:7": { status: false, letter: "" },
    "10:8": { status: false, letter: "" },
    "10:9": { status: false, letter: "" },
    "10:10": { status: false, letter: "" }
  },


  // Board 1

  {
    "1:1": { status: true, letter: "G", start: "1" },
    "1:2": { status: true, letter: "U" },
    "1:3": { status: true, letter: "R" },
    "1:4": { status: true, letter: "U", start: "2" },
    "1:5": { status: false, letter: "" },
    "1:6": { status: false, letter: "" },
    "1:7": { status: false, letter: "" },
    "1:8": { status: false, letter: "" },
    "1:9": { status: false, letter: "" },
    "1:10": { status: false, letter: "" },
    
    "2:1": { status: false, letter: "" },
    "2:2": { status: false, letter: "" },
    "2:3": { status: false, letter: "" },
    "2:4": { status: true, letter: "T", start: "3" },
    "2:5": { status: true, letter: "O" },
    "2:6": { status: true, letter: "M" },
    "2:7": { status: true, letter: "T", start: "4" },
    "2:8": { status: true, letter: "E" },
    "2:9": { status: false, letter: "" },
    "2:10": { status: false, letter: "" },

    "3:1": { status: true, letter: "F", start: "5" },
    "3:2": { status: false, letter: "" },
    "3:3": { status: false, letter: "" },
    "3:4": { status: true, letter: "T" },
    "3:5": { status: false, letter: "" },
    "3:6": { status: false, letter: "" },
    "3:7": { status: true, letter: "O" },
    "3:8": { status: false, letter: "" },
    "3:9": { status: false, letter: "" },
    "3:10": { status: false, letter: "" },

    "4:1": { status: true, letter: "O" },
    "4:2": { status: false, letter: "" },
    "4:3": { status: false, letter: "" },
    "4:4": { status: true, letter: "E" },
    "4:5": { status: false, letter: "" },
    "4:6": { status: true, letter: "S", start: "6" },
    "4:7": { status: true, letter: "T" },
    "4:8": { status: true, letter: "A" },
    "4:9": { status: true, letter: "R" },
    "4:10": { status: true, letter: "T" },

    "5:1": { status: true, letter: "T" },
    "5:2": { status: false, letter: "" },
    "5:3": { status: false, letter: "" },
    "5:4": { status: true, letter: "R" },
    "5:5": { status: false, letter: "" },
    "5:6": { status: false, letter: "" },
    "5:7": { status: true, letter: "E" },
    "5:8": { status: false, letter: "" },
    "5:9": { status: false, letter: "" },
    "5:10": { status: false, letter: "" },

    "6:1": { status: true, letter: "B", start: "7" },
    "6:2": { status: true, letter: "O" },
    "6:3": { status: true, letter: "L" },
    "6:4": { status: true, letter: "I" },
    "6:5": { status: true, letter: "B" },
    "6:6": { status: true, letter: "O" },
    "6:7": { status: true, letter: "M" },
    "6:8": { status: true, letter: "P", start: "8" },
    "6:9": { status: true, letter: "A" },
    "6:10": { status: false, letter: "" },

    "7:1": { status: true, letter: "O" },
    "7:2": { status: false, letter: "" },
    "7:3": { status: false, letter: "" },
    "7:4": { status: true, letter: "K" },
    "7:5": { status: false, letter: "" },
    "7:6": { status: false, letter: "" },
    "7:7": { status: false, letter: "" },
    "7:8": { status: true, letter: "O" },
    "7:9": { status: false, letter: "" },
    "7:10": { status: false, letter: "" },

    "8:1": { status: true, letter: "L", start: "9" },
    "8:2": { status: true, letter: "A" },
    "8:3": { status: true, letter: "S" },
    "8:4": { status: true, letter: "E" },
    "8:5": { status: true, letter: "R" },
    "8:6": { status: false, letter: "" },
    "8:7": { status: false, letter: "" },
    "8:8": { status: true, letter: "L" },
    "8:9": { status: false, letter: "" },
    "8:10": { status: false, letter: "" },

    "9:1": { status: true, letter: "L" },
    "9:2": { status: false, letter: "" },
    "9:3": { status: false, letter: "" },
    "9:4": { status: true, letter: "L" },
    "9:5": { status: false, letter: "" },
    "9:6": { status: false, letter: "" },
    "9:7": { status: false, letter: "" },
    "9:8": { status: true, letter: "I" },
    "9:9": { status: false, letter: "" },
    "9:10": { status: false, letter: "" },

    "10:1": { status: false, letter: "" },
    "10:2": { status: false, letter: "" },
    "10:3": { status: true, letter: "S", start: "10" },
    "10:4": { status: true, letter: "P" },
    "10:5": { status: true, letter: "A" },
    "10:6": { status: false, letter: "" },
    "10:7": { status: false, letter: "" },
    "10:8": { status: true, letter: "S" },
    "10:9": { status: false, letter: "" },
    "10:10": { status: false, letter: "" }
  },


  // Board 2

  {
    "1:1": { status: true, letter: "A", start: "1" },
    "1:2": { status: true, letter: "U" },
    "1:3": { status: true, letter: "R" },
    "1:4": { status: true, letter: "U", start: "2" },
    "1:5": { status: false, letter: "" },
    "1:6": { status: false, letter: "" },
    "1:7": { status: false, letter: "" },
    "1:8": { status: false, letter: "" },
    "1:9": { status: false, letter: "" },
    "1:10": { status: false, letter: "" },

    "2:1": { status: false, letter: "" },
    "2:2": { status: false, letter: "" },
    "2:3": { status: false, letter: "" },
    "2:4": { status: true, letter: "T", start: "3" },
    "2:5": { status: true, letter: "O" },
    "2:6": { status: true, letter: "M" },
    "2:7": { status: true, letter: "T", start: "4" },
    "2:8": { status: true, letter: "E" },
    "2:9": { status: false, letter: "" },
    "2:10": { status: false, letter: "" },

    "3:1": { status: true, letter: "F", start: "5" },
    "3:2": { status: false, letter: "" },
    "3:3": { status: false, letter: "" },
    "3:4": { status: true, letter: "T" },
    "3:5": { status: false, letter: "" },
    "3:6": { status: false, letter: "" },
    "3:7": { status: true, letter: "O" },
    "3:8": { status: false, letter: "" },
    "3:9": { status: false, letter: "" },
    "3:10": { status: false, letter: "" },

    "4:1": { status: true, letter: "O" },
    "4:2": { status: false, letter: "" },
    "4:3": { status: false, letter: "" },
    "4:4": { status: true, letter: "E" },
    "4:5": { status: false, letter: "" },
    "4:6": { status: true, letter: "S", start: "6" },
    "4:7": { status: true, letter: "T" },
    "4:8": { status: true, letter: "A" },
    "4:9": { status: true, letter: "R" },
    "4:10": { status: true, letter: "T" },

    "5:1": { status: true, letter: "T" },
    "5:2": { status: false, letter: "" },
    "5:3": { status: false, letter: "" },
    "5:4": { status: true, letter: "R" },
    "5:5": { status: false, letter: "" },
    "5:6": { status: false, letter: "" },
    "5:7": { status: true, letter: "E" },
    "5:8": { status: false, letter: "" },
    "5:9": { status: false, letter: "" },
    "5:10": { status: false, letter: "" },

    "6:1": { status: true, letter: "B", start: "7" },
    "6:2": { status: true, letter: "O" },
    "6:3": { status: true, letter: "L" },
    "6:4": { status: true, letter: "I" },
    "6:5": { status: true, letter: "B" },
    "6:6": { status: true, letter: "O" },
    "6:7": { status: true, letter: "M" },
    "6:8": { status: true, letter: "P", start: "8" },
    "6:9": { status: true, letter: "A" },
    "6:10": { status: false, letter: "" },

    "7:1": { status: true, letter: "O" },
    "7:2": { status: false, letter: "" },
    "7:3": { status: false, letter: "" },
    "7:4": { status: true, letter: "K" },
    "7:5": { status: false, letter: "" },
    "7:6": { status: false, letter: "" },
    "7:7": { status: false, letter: "" },
    "7:8": { status: true, letter: "O" },
    "7:9": { status: false, letter: "" },
    "7:10": { status: false, letter: "" },

    "8:1": { status: true, letter: "L", start: "9" },
    "8:2": { status: true, letter: "A" },
    "8:3": { status: true, letter: "S" },
    "8:4": { status: true, letter: "E" },
    "8:5": { status: true, letter: "R" },
    "8:6": { status: false, letter: "" },
    "8:7": { status: false, letter: "" },
    "8:8": { status: true, letter: "L" },
    "8:9": { status: false, letter: "" },
    "8:10": { status: false, letter: "" },

    "9:1": { status: true, letter: "L" },
    "9:2": { status: false, letter: "" },
    "9:3": { status: false, letter: "" },
    "9:4": { status: true, letter: "L" },
    "9:5": { status: false, letter: "" },
    "9:6": { status: false, letter: "" },
    "9:7": { status: false, letter: "" },
    "9:8": { status: true, letter: "I" },
    "9:9": { status: false, letter: "" },
    "9:10": { status: false, letter: "" },

    "10:1": { status: false, letter: "" },
    "10:2": { status: false, letter: "" },
    "10:3": { status: true, letter: "S", start: "10" },
    "10:4": { status: true, letter: "P" },
    "10:5": { status: true, letter: "A" },
    "10:6": { status: false, letter: "" },
    "10:7": { status: false, letter: "" },
    "10:8": { status: true, letter: "S" },
    "10:9": { status: false, letter: "" },
    "10:10": { status: false, letter: "" }
  },


  // Board 3

];


export function generate_board(index) {
    return boards[index];
}