export const initial_board = {
    "1:1": { status: true, letter: "", start_of_word: "1" },
    "1:2": { status: true, letter: "" },
    "1:3": { status: true, letter: "", start_of_word: "2" },
    "1:4": { status: true, letter: "" },
    "1:5": { status: false, letter: "" },
    "1:6": { status: true, letter: "", start_of_word: "3" },
    "1:7": { status: true, letter: "", start_of_word: "4" },
    "1:8": { status: true, letter: "" },
    "1:9": { status: false, letter: "" },
    "1:10": { status: true, letter: "", start_of_word: "5" },

    "2:1": { status: false, letter: "" },
    "2:2": { status: false, letter: "" },
    "2:3": { status: true, letter: "" },
    "2:4": { status: false, letter: "" },
    "2:5": { status: false, letter: "" },
    "2:6": { status: false, letter: "" },
    "2:7": { status: true, letter: "" },
    "2:8": { status: false, letter: "" },
    "2:9": { status: false, letter: "" },
    "2:10": { status: true, letter: "" },

    "3:1": { status: true, letter: "", start_of_word: "6" },
    "3:2": { status: true, letter: "" },
    "3:3": { status: true, letter: "" },
    "3:4": { status: false, letter: "" },
    "3:5": { status: true, letter: "", start_of_word: "7" },
    "3:6": { status: true, letter: "" },
    "3:7": { status: true, letter: "" },
    "3:8": { status: true, letter: "" },
    "3:9": { status: false, letter: "" },
    "3:10": { status: true, letter: "" },

    "4:1": { status: false, letter: "" },
    "4:2": { status: false, letter: "" },
    "4:3": { status: false, letter: "" },
    "4:4": { status: false, letter: "" },
    "4:5": { status: false, letter: "" },
    "4:6": { status: false, letter: "" },
    "4:7": { status: true, letter: "" },
    "4:8": { status: false, letter: "" },
    "4:9": { status: false, letter: "" },
    "4:10": { status: false, letter: "" },

    "5:1": { status: false, letter: "" },
    "5:2": { status: false, letter: "" },
    "5:3": { status: false, letter: "" },
    "5:4": { status: false, letter: "" },
    "5:5": { status: false, letter: "" },
    "5:6": { status: false, letter: "" },
    "5:7": { status: false, letter: "" },
    "5:8": { status: false, letter: "" },
    "5:9": { status: false, letter: "" },
    "5:10": { status: false, letter: "" },

    "6:1": { status: false, letter: "" },
    "6:2": { status: false, letter: "" },
    "6:3": { status: false, letter: "" },
    "6:4": { status: false, letter: "" },
    "6:5": { status: false, letter: "" },
    "6:6": { status: false, letter: "" },
    "6:7": { status: false, letter: "" },
    "6:8": { status: false, letter: "" },
    "6:9": { status: false, letter: "" },
    "6:10": { status: false, letter: "" },

    "7:1": { status: false, letter: "" },
    "7:2": { status: false, letter: "" },
    "7:3": { status: false, letter: "" },
    "7:4": { status: false, letter: "" },
    "7:5": { status: false, letter: "" },
    "7:6": { status: false, letter: "" },
    "7:7": { status: false, letter: "" },
    "7:8": { status: false, letter: "" },
    "7:9": { status: false, letter: "" },
    "7:10": { status: false, letter: "" },

    "8:1": { status: false, letter: "" },
    "8:2": { status: false, letter: "" },
    "8:3": { status: false, letter: "" },
    "8:4": { status: false, letter: "" },
    "8:5": { status: false, letter: "" },
    "8:6": { status: false, letter: "" },
    "8:7": { status: false, letter: "" },
    "8:8": { status: false, letter: "" },
    "8:9": { status: false, letter: "" },
    "8:10": { status: false, letter: "" },

    "9:1": { status: false, letter: "" },
    "9:2": { status: false, letter: "" },
    "9:3": { status: false, letter: "" },
    "9:4": { status: false, letter: "" },
    "9:5": { status: false, letter: "" },
    "9:6": { status: false, letter: "" },
    "9:7": { status: false, letter: "" },
    "9:8": { status: false, letter: "" },
    "9:9": { status: false, letter: "" },
    "9:10": { status: false, letter: "" },

    "10:1": { status: false, letter: "" },
    "10:2": { status: false, letter: "" },
    "10:3": { status: false, letter: "" },
    "10:4": { status: false, letter: "" },
    "10:5": { status: false, letter: "" },
    "10:6": { status: false, letter: "" },
    "10:7": { status: false, letter: "" },
    "10:8": { status: false, letter: "" },
    "10:9": { status: false, letter: "" },
    "10:10": { status: false, letter: "" },
};
